server:
  port: 8085
  servlet:
    context-path: /api/courseworkWeb

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coursework_3_1
    username: postgres #museunidayapplication100museup500pYc2!Y5Z
    password: 123TOpero #postgres
  liquibase:
    change-log: classpath:db/liquibase/db.changelog-master.xml
    drop-first: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        ddl-auto: createDefContur-drop
  main:
    allow-bean-definition-overriding: true

  mail:
    host: mail.hosting.reg.ru
    username: info@museup.ru
    password: 5I9j3D2a
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

java:
  util:
    logging:
      FileHandler.pattern: classpath:MyApplication_%u-%g.log

saveFilePath : uploads


security:
  oauth2:
    client:
      clientId: 156394297884-n2squf6cqapf4e4c7e5v5dkcvjqjj57j.apps.googleusercontent.com
      clientSecret: 9APZ--VFzcYWLB466QNhHGTf
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        openid,
        email,
        profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
